### ISSUE TITLE
jbrowse 404 refSeqs.json

### ISSUE THREAD

**Issue by tdhock** [PeakLearner/PeakLearner#122]
@deltarod How to resolve this error from jbrowse?
```
Error message(s): Could not load reference sequence definitions. RequestError: Unable to load http://localhost:8080/Public/H3K4me3_TDH_ENCODE/data/seq/refSeqs.json status: 404. 
```
There are files in jbrowse/jbrowse/data/genomes/hg19.
I tried rebuilding jbrowse (cd jbrowse/jbrowse && ./setup.sh) but error persists.
Can you please advise about how to debug?
Should I try looking for a route corresponding to that URL?
I notice the same 404 error from production server, https://peaklearner.rc.nau.edu/Public/H3K4me3_TDH_ENCODE/

**Comment by deltarod** [comment]
Try deleting the genomes folder. The genomes folder might not have been setup correctly. Try uploading a single hub, and let it work its way through until it completes.

**Comment by tdhock** [comment]
two problems: 401 error when I try to login, 
![Screenshot-peaklearner-google-auth-error-401](https://user-images.githubusercontent.com/932850/145251556-038c373c-f2cc-406b-8b96-8219b2088305.png)

and 
```
INFO:     127.0.0.1:35474 - "GET /newHub HTTP/1.1" 200 OK
/home/tdhock/projects/PeakLearner/venv/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'rcdata.nau.edu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
INFO:     127.0.0.1:35474 - "PUT /uploadHubUrl HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/tdhock/projects/PeakLearner/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/tdhock/projects/PeakLearner/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/home/tdhock/projects/PeakLearner/venv/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/tdhock/projects/PeakLearner/venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/tdhock/projects/PeakLearner/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/tdhock/projects/PeakLearner/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/tdhock/projects/PeakLearner/venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/tdhock/projects/PeakLearner/venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/home/tdhock/projects/PeakLearner/venv/lib/python3.8/site-packages/starlette/middleware/sessions.py", line 75, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/tdhock/projects/PeakLearner/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/tdhock/projects/PeakLearner/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/tdhock/projects/PeakLearner/venv/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/tdhock/projects/PeakLearner/venv/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/tdhock/projects/PeakLearner/venv/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/tdhock/projects/PeakLearner/venv/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/home/tdhock/projects/PeakLearner/venv/lib/python3.8/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/tdhock/projects/PeakLearner/core/Hubs/routes.py", line 127, in uploadHubUrl
    output = Hubs.parseHub(db, hubUrl, authUser)
  File "/home/tdhock/projects/PeakLearner/core/Hubs/Hubs.py", line 225, in parseHub
    return createHubFromParse(db, parsed, user)
  File "/home/tdhock/projects/PeakLearner/core/Hubs/Hubs.py", line 231, in createHubFromParse
    genomesFile = parsed['genomesFile']
TypeError: 'NoneType' object is not subscriptable
INFO:     127.0.0.1:35478 - "GET /login HTTP/1.1" 302 Found
```

**Comment by tdhock** [comment]
for the login problem, try `mv PeakLearnerTestConfig.cfg PeakLearner.cfg`

**Comment by tdhock** [comment]
uploading another hub fixed the TypeError.
rebuilding jbrowse fixed the jbrowse error.
